package it.smartcommunitylab.platform.idea.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Call service. Represents a row in the &quot;IM_Call&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.smartcommunitylab.platform.idea.model.impl.CallModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.smartcommunitylab.platform.idea.model.impl.CallImpl}.
 * </p>
 *
 * @author mirko perillo
 * @see Call
 * @see it.smartcommunitylab.platform.idea.model.impl.CallImpl
 * @see it.smartcommunitylab.platform.idea.model.impl.CallModelImpl
 * @generated
 */
public interface CallModel extends BaseModel<Call>, StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a call model instance should use the {@link Call} interface instead.
     */

    /**
     * Returns the primary key of this call.
     *
     * @return the primary key of this call
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this call.
     *
     * @param primaryKey the primary key of this call
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this call.
     *
     * @return the uuid of this call
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this call.
     *
     * @param uuid the uuid of this call
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the title of this call.
     *
     * @return the title of this call
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this call.
     *
     * @param title the title of this call
     */
    public void setTitle(String title);

    /**
     * Returns the call ID of this call.
     *
     * @return the call ID of this call
     */
    public long getCallId();

    /**
     * Sets the call ID of this call.
     *
     * @param callId the call ID of this call
     */
    public void setCallId(long callId);

    /**
     * Returns the group ID of this call.
     *
     * @return the group ID of this call
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this call.
     *
     * @param groupId the group ID of this call
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this call.
     *
     * @return the company ID of this call
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this call.
     *
     * @param companyId the company ID of this call
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this call.
     *
     * @return the user ID of this call
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this call.
     *
     * @param userId the user ID of this call
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this call.
     *
     * @return the user uuid of this call
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this call.
     *
     * @param userUuid the user uuid of this call
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this call.
     *
     * @return the user name of this call
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this call.
     *
     * @param userName the user name of this call
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this call.
     *
     * @return the create date of this call
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this call.
     *
     * @param createDate the create date of this call
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this call.
     *
     * @return the modified date of this call
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this call.
     *
     * @param modifiedDate the modified date of this call
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the description of this call.
     *
     * @return the description of this call
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this call.
     *
     * @param description the description of this call
     */
    public void setDescription(String description);

    /**
     * Returns the deadline of this call.
     *
     * @return the deadline of this call
     */
    public Date getDeadline();

    /**
     * Sets the deadline of this call.
     *
     * @param deadline the deadline of this call
     */
    public void setDeadline(Date deadline);

    /**
     * Returns the publication deadline of this call.
     *
     * @return the publication deadline of this call
     */
    public Date getPublicationDeadline();

    /**
     * Sets the publication deadline of this call.
     *
     * @param publicationDeadline the publication deadline of this call
     */
    public void setPublicationDeadline(Date publicationDeadline);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(it.smartcommunitylab.platform.idea.model.Call call);

    @Override
    public int hashCode();

    @Override
    public CacheModel<it.smartcommunitylab.platform.idea.model.Call> toCacheModel();

    @Override
    public it.smartcommunitylab.platform.idea.model.Call toEscapedModel();

    @Override
    public it.smartcommunitylab.platform.idea.model.Call toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
